#!/usr/bin/env python3
"""changelog.py — Generate CHANGELOG.md from git history.

Usage:
    python changelog.py [--repo PATH] [--output FILE]

Categorizes commits since the last tag into: Added / Fixed / Changed / Removed.
"""

import argparse
import datetime
import os
import re
import subprocess
import sys


def git(*args, cwd="."):
    res = subprocess.run(
        ["git"] + list(args),
        capture_output=True, text=False, cwd=cwd,
        timeout=30
    )
    stdout = res.stdout.decode("utf-8", errors="replace")
    return stdout.strip(), res.returncode


def get_last_tag(repo):
    tag, rc = git("describe", "--tags", "--abbrev=0", cwd=repo)
    return tag if rc == 0 else None


def get_first_commit(repo):
    commit, rc = git("rev-list", "--max-parents=0", "HEAD", cwd=repo)
    return commit if rc == 0 else None


def get_commits_since(repo, ref):
    log_fmt = "%H||%s||%B"
    raw, rc = git("log", f"{ref}..HEAD", f"--format={log_fmt}", "--no-merges", cwd=repo)
    if rc != 0:
        return []
    commits = []
    for entry in raw.split("\n\n"):
        lines = entry.strip().split("\n")
        if not lines:
            continue
        parts = lines[0].split("||", 2)
        if len(parts) >= 2:
            h, s = parts[0], parts[1]
            b = "\n".join(lines[1:]) if len(lines) > 1 else ""
            commits.append((h, s, b))
    return commits


def categorize(subject, body):
    text = (subject + " " + body).lower()
    if re.search(r'^(add|feat|feature|new|implement|create)', text):
        return "Added"
    if re.search(r'^(fix|bug|hotfix|patch|correct|repair)', text):
        return "Fixed"
    if re.search(r'^(remove|delete|drop|deprecat|cleanup)', text):
        return "Removed"
    return "Changed"


def generate(repo, output):
    last_tag = get_last_tag(repo)
    first_commit = get_first_commit(repo)
    ref = last_tag or first_commit

    if not ref:
        print("Not a git repository or no commits found.")
        return False

    commits = get_commits_since(repo, ref)
    if not commits:
        print(f"No new commits since {ref[:8] if ref else 'beginning'}.")
        return False

    categorized = {"Added": [], "Fixed": [], "Changed": [], "Removed": []}
    for h, s, b in commits:
        cat = categorize(s, b)
        categorized[cat].append((h, s))

    today = datetime.date.today().isoformat()
    lines = [f"# Changelog", "", f"## {today}", ""]

    for cat in ["Added", "Fixed", "Changed", "Removed"]:
        items = categorized[cat]
        if items:
            lines.append(f"### {cat}")
            for h, s in items:
                lines.append(f"- {s} ({h[:7]})")
            lines.append("")

    lines.append("---")
    lines.append(f"*Generated by changelog.py on {today}*")
    lines.append("")

    body = "\n".join(lines)
    with open(output, "w", encoding="utf-8") as f:
        f.write(body)

    print(f"CHANGELOG written to {output} ({len(lines) - 1} lines, {len(commits)} commits)")
    print(f"  Added: {len(categorized['Added'])}")
    print(f"  Fixed: {len(categorized['Fixed'])}")
    print(f"  Changed: {len(categorized['Changed'])}")
    print(f"  Removed: {len(categorized['Removed'])}")
    return True


def main():
    parser = argparse.ArgumentParser(description="Generate CHANGELOG.md from git history")
    parser.add_argument("--repo", default=".", help="Path to git repository")
    parser.add_argument("--output", default="CHANGELOG.md", help="Output file path")
    args = parser.parse_args()

    if not generate(args.repo, args.output):
        sys.exit(1)


if __name__ == "__main__":
    main()
