#!/usr/bin/env bash
set -euo pipefail

CHANGELOG_FILE="${1:-CHANGELOG.md}"

if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "Error: not a git repository" >&2
  exit 1
fi

last_tag=$(git tag --list --sort=-v:refname | head -1)

if [ -z "$last_tag" ]; then
  range="HEAD"
  since_msg="initial commit"
else
  range="${last_tag}..HEAD"
  since_msg="$last_tag"
fi

cat > "$CHANGELOG_FILE" << EOF
# Changelog

## $(date +%Y-%m-%d)

Changes since **${since_msg}**:

EOF

categories="Added|Fixed|Changed|Removed|Documentation|Testing"

{
  git log --format="---%n%H%n%s%n%b" "$range" 2>/dev/null
} | while IFS= read -r line; do
  if [ "$line" != "---" ]; then
    continue
  fi

  IFS= read -r hash
  IFS= read -r subject
  IFS= read -r body

  if [ -z "$subject" ]; then
    continue
  fi

  type="Changed"
  case "$subject" in
    feat:*|feature:*|add:*|new:*)          type="Added" ;;
    fix:*|bugfix:*|bug:*|hotfix:*)         type="Fixed" ;;
    change:*|refactor:*|update:*|perf:*)   type="Changed" ;;
    remove:*|delete:*|deprecate:*|drop:*)  type="Removed" ;;
    docs:*|doc:*|readme:*)                 type="Documentation" ;;
    test:*|spec:*)                         type="Testing" ;;
  esac

  short_hash="${hash:0:7}"
  clean_msg=$(echo "$subject" | sed 's/\[/\\[/g; s/\]/\\]/g')
  printf "%s\t%s\t%s\n" "$type" "$clean_msg" "$short_hash"
done | sort -k1,1 > /tmp/_changelog_raw_$$

current_cat=""
while IFS=$'\t' read -r cat msg hash; do
  if [ "$cat" != "$current_cat" ]; then
    current_cat="$cat"
    {
      echo ""
      echo "### $cat"
      echo ""
    } >> "$CHANGELOG_FILE"
  fi
  echo "- $msg ($hash)" >> "$CHANGELOG_FILE"
done < /tmp/_changelog_raw_$$

rm -f /tmp/_changelog_raw_$$

{
  echo ""
  echo "---"
  echo "_Generated by changelog.sh_"
} >> "$CHANGELOG_FILE"

echo "Wrote $CHANGELOG_FILE"
